from tkinter import *
root = Tk()
'''fx = Frame(root,borderwidth=15,bg='blue')
fx.pack(anchor='nw',side=TOP,pady=12)
lx = Label(fx,text='SUBJECTS',fg='dark blue',bg='light blue')
lx.pack()'''
f = Frame(root,borderwidth=15, bg = "blue")
f.pack()
a = Label(f,text="GUI MARKSHEET BY-SHUBHAM", fg="dark blue" , font="arial 10 bold",bg="light blue",padx=450,pady=20)
a.pack()
fx = Frame(root,borderwidth=10,bg='blue')
fx.pack(anchor='nw',side=TOP,pady=12)
lx = Label(fx,text='SUBJECTS                          MARKS                     GRADE   ',fg='dark blue',bg='light blue')
lx.pack()
#fy = Frame(root,borderwidth=15,bg='blue')
#fy.pack(side=TOP)
#ly = Label(fy,text='MARKS',fg='dark blue',bg='light blue')
#ly.pack()
f2 = Frame(root, borderwidth=10, bg = "blue")
f2.pack(anchor="nw",side=TOP, pady=12)
b = Label(f2,text="SCIENCE                  94/100                    A1      ", fg="dark blue", font="arial 10 italic ",bg="light blue")
b.pack()
f3= Frame(root, borderwidth=10, bg = "blue")
f3.pack(anchor="nw",side=TOP, pady=20)
b = Label(f3,text="MATHS                     93/100                  A2       ", fg="dark blue", font="arial 10 italic ",bg="light blue")
b.pack()
f4 = Frame(root, borderwidth=10, bg = "blue")
f4.pack(anchor="nw",side=TOP)
b = Label(f4,text="ENGLISH                 93/100                    A2      ", fg="dark blue", font="arial 10 italic ",bg="light blue")
b.pack()
f5 = Frame(root, borderwidth=10, bg = "blue")
f5.pack(anchor="nw",side=TOP,pady=20)
b = Label(f5,text="HINDI                        96/100                   A1      ", fg="dark blue", font="arial 10 italic ",bg="light blue")
b.pack()
f6 = Frame(root, borderwidth=10, bg = "blue")
f6.pack(anchor="nw",side=TOP,pady=10)
b = Label(f6,text="S.SCI                        90/100                   A2      ", fg="dark blue", font="arial 10 italic ",bg="light blue")
b.pack()
f10= Frame(root,borderwidth=10,bg='blue')
f10.pack(anchor='nw',side=TOP,pady=12)
l10= Label(f10,text='               PERCENTAGE                                                        93.2%           ',fg='dark blue',bg='light blue')
l10.pack()




root.mainloop()